# Generated by Django 2.2.7 on 2019-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191127_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='spam_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
