# Generated by Django 2.2.7 on 2019-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_spam_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
